title: Microwavin Manoa
description: A recipe sharing application for UH Manoa students
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: https://github.com/microwavin-manoa/microwavin-manoa
gems:
  - jekyll-mentions